server:
    port: 8888
spring:
    application:
        name: config
    profiles:
        active: dev
    cloud:
        config:
            server:
                git:
                    #配置git仓库地址
                    uri: https://github.com/yaxinjw/springcloudinactivity.git
                    #配置仓库路径
                    searchPaths: repo
                    #访问git仓库的用户名
                    username: readanger@163.com
                    #访问git仓库的用户密码
                    password: cs00236659
            #配置仓库的分支
            label: master
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/