server:
  port: 8763
spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: 192.168.137.2
    port: 5672
    username: admin
    password: 123456
    virtualHost: /
    publisherConfirms: true
  cloud:
    bus:
      trace:
        enabled: true

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      # 用来指定采样请求的百分比（默认为 0.1，即 10%）
      probability: 1

# Spring Boot 2.0 以后，actuator 默认只开启 health 和 info 端点，要使用 refresh 端点需要通过 management 指定
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh,httptrace