server:
  port: 8764
spring:
  application:
    name: eurekaclient

# Spring Boot 2.0 以后，actuator 默认只开启 health 和 info 端点，要使用 refresh 端点需要通过 management 指定
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
