server:
    port: 8081
spring:
    application:
        name: feign

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/


feign:
    hystrix:
        enabled: true